default: &default
  backend.url: http://cmpolwappbe01/
  token.header: X-polapp-token
  login.endpoint: v1/login
  search.endpoint: v1/search
  deleteFavorites.endpoint: v1/favorites
  details.endpoint: v1/progettodemand
  addFavorites.endpoint: v1/favorites
  getFavorites.endpoint: v1/favorites
  logout.endpoint: v1/logout
  
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
