///////////////////////////////////////////////////////////
//  IcoManager.as
//  Macromedia ActionScript Implementation of the Class IcoManager
//  Generated by Enterprise Architect
//  Created on:      29-ago-2010 19.14.21
//  Original author: marco
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.util
{
	/**
	 * @author marco
	 * @version 1.0
	 * @created 29-ago-2010 19.14.21
	 */
	public class IcoManager
	{
		public static const LOGO:Class;
		public static const INFO:Class;
		
		/*private static var instance:IcoManager;
		public static function getInstance():IcoManager
		{
			if(instance == null)
			{
				instance = new IcoManager(new HideClass());
			}
		}*/
		
		// Embed icon image.
        //[Embed(source='assets/globe.jpg')]
        //public var globeImage:Class;
		//public function IcoManager(hide:HideClass){
		//}
		//public function getIco(str:String):Class
		//{
		//} 

	}//end IcoManager
}
class HideClass{}