///////////////////////////////////////////////////////////
//  IHelp.as
//  Macromedia ActionScript Implementation of the Interface IHelp
//  Generated by Enterprise Architect
//  Created on:      29-ago-2010 12.11.25
//  Original author: marco
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.util
{
	import mx.core.IUIComponent;

	/**
	 * I componenti che implementano questa interfaccia sono in grado di fornire un ID
	 * riferente ad un testo di aiuto.
	 * @author marco
	 * @version 1.0
	 * @created 29-ago-2010 12.11.25
	 */
	public interface IHelp extends IUIComponent
	{
		function getIDHelp(): String;
	}//end IHelp

}