///////////////////////////////////////////////////////////
//  MessageManager.as
//  Macromedia ActionScript Implementation of the Class MessageManager
//  Generated by Enterprise Architect
//  Created on:      29-ago-2010 16.05.46
//  Original author: marco
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.util
{
	import flash.utils.Dictionary;
	
	/**
	 * @author Marco Salonia
	 * @version 1.0
	 * @created 29-ago-2010 16.05.46
	 */
	public class LabelStringManager
	{
		private static var instance:LabelStringManager;
		public static function getInstance():LabelStringManager
		{
			if(instance == null)
			{
				instance = new LabelStringManager(new HideClass());
			}
			return instance;
		}
		private var dict:Dictionary;
		public function LabelStringManager(hide:HideClass){
			dict = new Dictionary();
			dict["titleBoxTreeFascicolo"] 	= "io sono box titleBoxTreeFascicolo";
			dict["upTreeFascicolo"] 		= "io sono upTreeFascicolo";
			dict["boxTree"] = "io sono box tree";
			dict["boxView"]	= "io sono box view";
		}
		public function getImportance( id:String ):String
		{
			return "";
		}
		public function existMessage( idMessage:String ):Boolean
		{
			return true;
			if(idMessage==null || idMessage.length==0)
			{
				return false;
			}
			var msg:String = findMessage( idMessage );
			return (msg != null  && msg.length>0);
		}
		public function findMessage(idMessage:String):String
		{
			// TODO implementazione
			return dict[idMessage];
		}
	}//end MessageManager
}

class HideClass{}