///////////////////////////////////////////////////////////
//  ConstCommand.as
//  Macromedia ActionScript Implementation of the Class ConstCommand
//  Generated by Enterprise Architect
//  Created on:      26-ago-2010 9.43.32
//  Original author: marco
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.controller
{
	import com.li.dc.sebc.turboFSE.fseTurbo;
	/**
	 * @author Marco Salonia
	 * @version 1.0
	 * @created 26-ago-2010 9.43.32
	 */
	public class ConstCommand
	{
		use namespace fseTurbo;

		static public const RICHIEDI_URL_IMMAGINE: String 	= "richiediUrlImmagine";
		static public const INIT_SMART_CARD: String 		= "initSmartCard";
		static public const START_APPLICATION: String 		= "start_application";

		static public const LOAD_INIT_QUERY: String 		= "load_init_query";
		static public const LOAD_CONFIGURATION: String  	= "load_configuration";
		static public const CONF_DEBUG: String 				= "conf_debug";
		static public const CONF_LABEL: String 				= "conf_label";

		static public const PUSH_MEMENTO: String 			= "pushMemento";
		static public const UNDO: String 					= "undo";
		static public const REDO: String 					= "redo";

		static public const RESET_IDENTIFICA: String 				= "resetIdentifica";
		static public const INTERROGA_ASCOLTATORE_TESTUALE: String 	= "interrogaAscoltatoreTestuale";
		static public const INTERROGA_ASCOLTATORE_CDA2: String 		= "interrogaAscoltatoreCDA2";
		static public const IDENTIFICA_CITTADINO: String 			= "identificaCittadino";
		static public const LOAD_ELENCO_COMUNI: String 				= "loadElencoComuni";
		static public const LOAD_ELENCO_PROVINCE: String 			= "loadElencoProvince";
		static public const VISUALIZZA_VALIDATE_ERROR: String 		= "visualizzaValidateError";
		static public const SMART_CARD_CITT_READY: String 			= "smartCardCittReady";
		static public const AGGIORNA_FASCICOLO: String 				= "aggiornaFascicolo";
		static public const AGGIORNA_FLUSSI: String 				= "aggiornaFlussi";
		static public const AGGIORNA_CLASSIFICAZIONI: String 		= "aggiornaClassificazioni";
		static public const AGGIORNA_TIMELINE: String 				= "aggiornaTimeline";
		static public const AGGIORNA_CHANGE_TAB: String 			= "aggiornaChangeTab";

		static public const LOAD_OPERATORE: String 					= "loadOperatore";
		static public const LOAD_CITTADINO_SMART_CARD: String 		= "loadCittadinoSmarCard";
		static public const EXPAND_VIEW: String 					= "expandView";
		static public const APRI_PANEL_FILTRI: String 				= "apriPanelFiltri";
		static public const CHIUDI_PANEL_FILTRI: String 			= "chiudiPanelFiltri";
		static public const LOAD_GADO: String 						= "loadGado";
		static public const APRI_PDT: String 						= "apriPdt";
		static public const CHIUDI_PDT: String 						= "chiudiPdt";
		static public const ADD_PDT_IN_FASCICOLO: String 			= "addPdtInFascicolo";

		static public const CLOSE_PDT_IN_FASCICOLO: String 			= "closePdtInFascicolo";
		static public const OPEN_PDT_SERVICE: String 				= "openPdtService";
		static public const CLOSE_PDT_SERVICE: String 				= "closePdtService";
		static public const REFRESH_FOLDER_PDT: String 				= "refreshFolderPdt";
		static public const UPDATE_PDT: String 						= "updatePdt";

		static public const UPDATE_CONTENT_FOLDER: String 			= "updateContentFolder";
		static public const UPDATE_FOLDER: String 					= "updateFolder";
		static public const UPDATE_FLUSSI: String 					= "updateFlussi";
		static public const UPDATE_FILTRI: String 					= "updateFiltri";

		static public const FILTRA_DATA_TREE: String 				= "filtraDataTree";
		static public const LOAD_CONTENT_FOLDER: String 			= "loadContentFolder";
		static public const UPDATE_DOWN_ITEM_TREE: String 			= "updateDownItemTree";
		static public const DAMMI_TIMELINE:String 					= "dammiTimeline";
		//
		static public const DAMMI_FSEPS: String 			= "dammiFseps";
	    static public const DAMMI_ALBERO: String 			= "dammiAlbero";
	    static public const DAMMI_FLUSSI: String 			= "dammiFlussi";
	    static public const GO_HOME: String 				= "goHome";
	    static public const GO_TEMPORALE: String 			= "goTemporale";
	    static public const LOAD_ALL_TREE: String 			= "loadAllTree";
	    static public const APRI_PANEL_FILTRI_FLUSSI: String 		= "apriPanelFiltriFlussi";
	    static public const AUTORIZZA_DCE: String 			= "autorizzaDce";
	    static public const OTTIENI_DOCUMENTO: String 		= "ottieniDocumento";

		static public const RICHIEDI_URL_TESTO_REFERTO:String = "richiediUrlTestoReferto";
		static public const OTTIENI_TESTO_REFERTO:String = "ottieniTestoReferto";

		static public const LOAD_PARAMETRI_VARIABILI:String = "loadParametriVariabili";

 	}//end ConstCommand
}