///////////////////////////////////////////////////////////
//  AbstractService.as
//  Macromedia ActionScript Implementation of the Class AbstractService
//  Generated by Enterprise Architect
//  Created on:      31-ago-2010 18:06:33
//  Original author: marco
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.business
{
	import mx.rpc.IResponder;
	 
	/**
	 * Dispatch di eventi di errore di fault e result
	 * @author marco
	 * @version 1.0
	 * @updated 31-ago-2010 18:12:02
	 */
	public class TurboService
	{
	    public var responder: IResponder;
		public function TurboService(responder:IResponder = null)
		{
			this.responder = responder;
		}
	    virtual public function execute( ): void
	    {
	    	throw new Error("This is a AbstractService execute, override in a subclass");
	    }
	    
	}//end AbstractService
}