///////////////////////////////////////////////////////////
//  RedoMementoCommand.as
//  Macromedia ActionScript Implementation of the Class RedoMementoCommand
//  Generated by Enterprise Architect
//  Created on:      30-ago-2010 23:50:55
//  Original author: marco
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.controller.commands
{
	 
	import it.lispa.siss.sebc.flex.mvc.controller.Command;

	/**
	 * @author marco
	 * @version 1.0
	 * @created 30-ago-2010 23:50:55
	 */
	public class RedoMementoCommand extends Command
	{
		public function RedoMementoCommand(){

		}

	    /**
	     * 
	     * @param event
	     */
		override public function execute( data:Object = null ): void
	    {
	    }

	}//end RedoMementoCommand

}