///////////////////////////////////////////////////////////
//  UndoMementoCommand.as
//  Macromedia ActionScript Implementation of the Class UndoMementoCommand
//  Generated by Enterprise Architect
//  Created on:      26-ago-2010 1.20.59
//  Original author: marco
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.controller.commands
{
	  
	import it.lispa.siss.sebc.flex.memento.ManagerMemento;
	import it.lispa.siss.sebc.flex.mvc.controller.Command;

	/**
	 * @author marco
	 * @version 1.0
	 * @created 26-ago-2010 1.20.59
	 */
	public class UndoMementoCommand extends Command
	{
		public function UndoMementoCommand(){

		}
		override public function execute(data:Object = null):void
		{
			 ManagerMemento.getInstance().undo();
		}
	}//end UndoMementoCommand
}