///////////////////////////////////////////////////////////
//  FSEModel.as
//  Macromedia ActionScript Implementation of the Class FSEModel
//  Generated by Enterprise Architect
//  Created on:      26-ago-2010 23.36.21
//  Original author: marco
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.model
{
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataAreaTab;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataCittadino;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataConfiguration;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataDownTree;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataElencoCittadini;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataFlussiSelect;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataFolderSelect;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataOperatore;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataPDTClose;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataPDTOpen;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataSmartCardCitt;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataTree;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataTreeFlussi;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataUpFlussi;
	import com.li.dc.sebc.turboFSE.model.dataProxy.DataUpTree;
	import com.li.dc.sebc.turboFSE.model.dataProxy.StateAreaLavoro;
	import com.li.dc.sebc.turboFSE.model.dataProxy.StateAssistito;
	import com.li.dc.sebc.turboFSE.model.dataProxy.StateIdentificaCittadino;
	import com.li.dc.sebc.turboFSE.model.dataProxy.StateLogo;
	import com.li.dc.sebc.turboFSE.model.dataProxy.StateStack;
	import com.li.dc.sebc.turboFSE.model.dataProxy.TextNavigationLabelProxy;
	import com.li.dc.sebc.turboFSE.view.component.PanelFiltriFlussi;
	import com.li.dc.sebc.turboFSE.view.component.PanelPDT;
	import com.li.dc.sebc.turboFSE.view.nodeView.PanelFilters;

	import flash.utils.Dictionary;

	import it.lisit.siss.flex.communication.coop.IFactoryCOOP;
	import it.lisit.siss.flex.communication.crm.IFactoryCRM;
	import it.lisit.siss.flex.communication.fse.IFactoryFSE;
	import it.lisit.siss.flex.communication.icce.IFactoryICCE;
	import it.lisit.siss.flex.communication.sa.IFactorySA;
	import it.lisit.siss.flex.communication.util.IFactoryUtils;
	import it.lispa.siss.sebc.flex.collection.HashTable;
	import it.lispa.siss.sebc.flex.mvc.model.Model;
	import it.lispa.siss.sebc.flex.mvc.model.proxy.ArrayProxy;
	import it.lispa.siss.sebc.flex.mvc.model.proxy.BooleanProxy;
	import it.lispa.siss.sebc.flex.mvc.model.proxy.DataProxy;
	import it.lispa.siss.sebc.flex.mvc.model.proxy.StringProxy;
	import it.lispa.siss.sebc.middleground.entity.Cittadino;
	import it.lispa.siss.sebc.middleground.entity.Operatore;

	import mx.core.Application;

	/**
	 * @author marco
	 * @version 1.0
	 * @created 26-ago-2010 23.36.21
	 */
	[Bindable]
	public class FSEModel extends Model
	{
		private static var instance:FSEModel;
		public static function getInstance():FSEModel
		{
			if(instance == null)
			{
				instance = new FSEModel(   );
			}
			return instance;
		}
		public function FSEModel( ){
			super();
			if(instance!=null)
			{
				throw new Error("");
			}
			instance = this;
		}
		override protected function initialize():void
		{
			registerData( ConstDataProxy.DATA_SELECT_BUTTON,new DataProxy());
			registerData( ConstDataProxy.DATA_AREATAB,new DataAreaTab());
			registerData( ConstDataProxy.DATA_CITTADINO,new DataCittadino());
			registerData( ConstDataProxy.DATA_CONFIGURATION,new DataConfiguration());
			registerData( ConstDataProxy.DATA_OPERATORE,new DataOperatore());
			registerData( ConstDataProxy.DATA_ELENCO_CITTADINI,new DataElencoCittadini());

			registerData( ConstDataProxy.DATA_TREE,new DataTree());
			registerData( ConstDataProxy.DATA_TREE_FLUSSI,new DataTreeFlussi());
			registerData( ConstDataProxy.DATA_VISIBLE_UP_FLUSSI,new DataUpFlussi());

			registerData( ConstDataProxy.DATA_VISIBLE_UP_TREE,new DataUpTree());

			registerData( ConstDataProxy.DATA_DOWN_TREE,new DataDownTree());

			registerData( ConstDataProxy.DATA_PDT_OPEN, new DataPDTOpen());
			registerData( ConstDataProxy.DATA_PDT_CLOSE,new DataPDTClose());

			registerData( ConstDataProxy.TEXT_NAVIGATION_LABEL,new TextNavigationLabelProxy());

			registerData( ConstDataProxy.SMARTCARD_CIT,new DataSmartCardCitt(false));
			registerData( ConstDataProxy.STATE_AREA_LAVORO,new StateAreaLavoro());
			registerData( ConstDataProxy.STATE_ASSISTITO_FSE,new StateAssistito());
			registerData( ConstDataProxy.STATE_LOGO,new StateLogo());
			registerData( ConstDataProxy.STATE_STACK,new StateStack());
			registerData( ConstDataProxy.STATE_IDENTIFICA_CITTADINO,new StateIdentificaCittadino());


			registerData( ConstDataProxy.DATA_FOLDER_SELECT,new DataFolderSelect());
			registerData( ConstDataProxy.DATA_FLUSSI_SELECT,new DataFlussiSelect());

			registerData( ConstDataProxy.HEADER_FLUSSI_TEXT,new StringProxy());
			registerData( ConstDataProxy.DATA_MESSAGE,new StringProxy());


			registerData( ConstDataProxy.LIST_ENTE, new ArrayProxy());
			registerData( ConstDataProxy.LIST_EROGAZIONE, new ArrayProxy());
			registerData( ConstDataProxy.LIST_FOLDER, new ArrayProxy());
			registerData( ConstDataProxy.LIST_PRESIDIO, new ArrayProxy());


			registerData( ConstDataProxy.CLASSIFICAZIONI, new DataProxy( null ));

			//registerData( ConstDataProxy.DATA_TIMELINE, new DataProxy( null ));

			registerData( ConstDataProxy.OPENPOPUPTIMELINE, new BooleanProxy( false ));
		}
		//============STATI===============================
		public static const VERSION:String = "V 1.0.4";

		public var testArea:Boolean = false;

		/**
		 * destination è la classe java a cui puntano i remoteObject
		 */

		public var destination:String;
		public var host:String;

		public var documentoTestuale:Boolean 			= false;
		public var documentoCDA2:Boolean 				= false;

		public var enabledTabFascicolo:Boolean 			= false;
		public var enabledTabEventi:Boolean 			= false;
		public var enabledTabTimeLine:Boolean 			= false;
		public var enabledTabClassificazioni:Boolean 	= false;

		public var reloadRootFascicolo:Boolean 			= false;
		public var reloadRootFlussi:Boolean 			= false;
		public var reloadClassificazioni:Boolean 		= false;
		public var reloadTimeline:Boolean 				= false;

		public var maxSizeMemento:uint			= 10;
		public var oldIndexTab:uint				= 0;
		public var oldParamExpand:Object		= null;

		public var listButtonPDT:Array		= ['Apri PDT','Chiudi PDT'];
		public var listToolButtonBar:Array	= ["Filtri generici","Filtri data"];

		/**
		 *  Un dizionario contenente
		 *
		 */
		public var queryParams:Dictionary;

		/**
		 * indirizzo della home
		 */
		public var urlHome:String;



		//==================================================
		public var factoryFSE:IFactoryFSE;
		public var factoryCOOP:IFactoryCOOP;
		public var factoryICCE:IFactoryICCE;
		public var factoryCRM:IFactoryCRM;
		public var factorySA:IFactorySA;
		public var factoryUtil:IFactoryUtils;
		//==================================================
		public var cittadino:Cittadino;
		public var operatore:Operatore;

		public var hashTable:HashTable;
		public var hashViste:HashTable = new HashTable();
		public var turboApp:Application;
		public var elencoProvincie:Array;
		public var elencoComuni:Array;
		public var parametriVariabili:Object;
		//==================================================
		public var panelOpenPdt:PanelPDT;
		public var panelClosePdt:PanelPDT;
		public var panelFilters:PanelFilters;

		public var panelFiltersFlussi:PanelFiltriFlussi;

		public var colorBckPopup:uint = 0xFFFFFF;
		/* cioè con i setdocumentali */
		public var isTreeComplete:Boolean	= false;


		public var startYearTimeline:int 	= 0;
		public var endYearTimeline:int 		= 0;
		////////////////////////////////////////
		private var _dateToday:Date;
		public function get today():Date
		{
			if(_dateToday==null)
			{
				_dateToday = new Date();
			}
			return _dateToday;
		}
	}//end FSEModel
}
