///////////////////////////////////////////////////////////
//  DammiAlberoCommand.as
//  Macromedia ActionScript Implementation of the Class DammiAlberoCommand
//  Generated by Enterprise Architect
//  Created on:      30-ago-2010 23:52:07
//  Original author: Marco Salonia
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.controller.commands.serviceCommand
{
	 
	import com.li.dc.sebc.turboFSE.business.FactoryService;
	import com.li.dc.sebc.turboFSE.model.ConstDataProxy;
	import com.li.dc.sebc.turboFSE.model.FSEModel;
	import com.li.dc.sebc.turboFSE.model.vo.RispostaTree;
	import com.li.dc.sebc.turboFSE.model.vo.Tree;
	import com.li.dc.sebc.turboFSE.util.WrapResponder;
	
	import it.lispa.siss.sebc.flex.messages.ConstStatus;
	import it.lispa.siss.sebc.flex.messages.Message;
	import it.lispa.siss.sebc.flex.messages.MessageManager;
	
	import mx.collections.ArrayCollection;

	/**
	 * @author Marco Salonia
	 * @version 1.0
	 * @created 30-ago-2010 23:52:07
	 */
	public class DammiAlberoCommand extends ControlWait
	{
		public function DammiAlberoCommand()
		{
			super();
		}
		override protected function executeCommand(data:Object=null):void
		{
			var m:FSEModel = FSEModel.getInstance();
			if(data!=null && data is String)
			{
				var order:String = data as String;
	    		FactoryService.getInstance().getTree( new WrapResponder( this ), Number(order) ).execute();
			}
		}
		 
		override protected function executeResult(data:Object):void
		{
			if(data is RispostaTree)
			{
				var risposta:RispostaTree	=  data as RispostaTree;
				
				// ===== Obbligo l'appp a ricaricare i dati tramite la consultaDocumenti. ====
				FSEModel.getInstance().isTreeComplete	= false;
				
				if(risposta.esitoNegativo!=null )
				{
					MessageManager.getInstance().addMessage( risposta.esitoNegativo );
				}else if(risposta.fault!=null)
				{
					MessageManager.getInstance().addMessage( risposta.fault );
				}else
				{
					var flag:Boolean	= false;
					var tree:Tree = risposta.tree;
					if(tree!=null)
					{
						var lista:ArrayCollection = tree.listaFolder;
						if(lista!=null && lista.length>0)
						{
							flag = true;
							FSEModel.getInstance().retrieveProxy(ConstDataProxy.DATA_TREE).update( risposta.tree );
						}
					}
					if(risposta.listaWarning!=null)
					{
						MessageManager.getInstance().addMessage( risposta.listaWarning );	
					}else
					{
						if(!flag){
							var msg:String	= "Non è presente una lista";
							MessageManager.getInstance().addMessage( new Message("Attenzione",msg,ConstStatus.WARNING) );
						}
					}
				}
			}	 
		}
		override protected function executeFault(info:Object):void
		{
			MessageManager.getInstance().addMessage( info );
		}
	}//end DammiAlberoCommand
}