///////////////////////////////////////////////////////////
//  DammiAlberoCommand.as
//  Macromedia ActionScript Implementation of the Class DammiAlberoCommand
//  Generated by Enterprise Architect
//  Created on:      30-ago-2010 23:52:07
//  Original author: Marco Salonia
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.controller.commands.serviceCommand
{
	 
	import com.li.dc.sebc.turboFSE.business.FactoryService;
	import com.li.dc.sebc.turboFSE.model.ConstDataProxy;
	import com.li.dc.sebc.turboFSE.model.FSEModel;
	import com.li.dc.sebc.turboFSE.model.vo.RispostaTree;
	import com.li.dc.sebc.turboFSE.model.vo.Tree;
	import com.li.dc.sebc.turboFSE.util.JSManager;
	import com.li.dc.sebc.turboFSE.util.WrapResponder;
	
	import it.lispa.siss.sebc.flex.messages.ConstStatus;
	import it.lispa.siss.sebc.flex.messages.Message;
	import it.lispa.siss.sebc.flex.messages.MessageManager;
	
	import mx.collections.ArrayCollection;

	/**
	 * @author Marco Salonia
	 * @version 1.0
	 * @created 30-ago-2010 23:52:07
	 */
	public class DammiFsepsCommand extends ControlWait
	{
		public function DammiFsepsCommand()
		{
			super();
		}
		override protected function executeCommand(data:Object=null):void
		{
			var m:FSEModel = FSEModel.getInstance();
			if(data!=null && data is String)
			{
				var url:String = data as String;
	    		FactoryService.getInstance().getUrlFseps( new WrapResponder( this ), url ).execute();
			}
		}
		 
		override protected function executeResult(data:Object):void
		{
			if(data is String)
			{
				var layout:Object		= JSManager.getInstance().getLayout();
				JSManager.getInstance().createWindow(data as String , Math.random().toString(),layout.x,layout.y,layout.w,layout.h);				
			}	 
		}
		override protected function executeFault(info:Object):void
		{
			MessageManager.getInstance().addMessage( info );
		}
		
	}//end DammiAlberoCommand
}