///////////////////////////////////////////////////////////
//  ContentFolderService.as
//  Macromedia ActionScript Implementation of the Class ContentFolderService
//  Generated by Enterprise Architect
//  Created on:      31-ago-2010 18:09:56
//  Original author: marco
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.business.remoteService
{
	import it.lispa.siss.sebc.flex.debug.Debug;
	import it.lispa.siss.sebc.middleground.entity.Cittadino;
	import it.lispa.siss.sebc.middleground.entity.Operatore;
	
	import mx.rpc.IResponder;

	/**
	 * @author Marco Salonia
	 * @version 1.0
	 * @created 31-ago-2010 18:09:56
	 */
	public class ContentFolderService extends RemoteService
	{
		 public var idFolder:String;
		 public var cittadino:Cittadino;
		 public var operatore:Operatore;
	    /**
	     * 
	     * @param id    L'identificativo del folder
	     */
	    public function ContentFolderService(responder:IResponder=null,destination:String=null,cittadino:Cittadino=null,operatore:Operatore=null,id:String=null): void
	    {
	    	super(responder,destination);
	    	this.cittadino = cittadino;
	    	this.operatore = operatore;
	    	this.idFolder  = id;
	    }
	    /**
	     * 
	     * @param responder
	     */
		override public function execute(): void
	    {
	    	Debug.logDebug( "ContentFolderService.execute cittadino "+cittadino+", operatore : "+operatore+", idFolder "+idFolder);
	    	
	    	if(cittadino!=null && operatore!=null && idFolder!=null){
	    		getRemote().getContentFolder( cittadino, operatore, idFolder );
	    	}else
	    	{
	    		Debug.logDebug( "ContentFolderService.execute callInternalFault ");
	    		callInternalFault("Un parametro risulta null");
	    	}
	    }

	}//end ContentFolderService

}