///////////////////////////////////////////////////////////
//  StartApplicationCommand.as
//  Macromedia ActionScript Implementation of the Class StartApplicationCommand
//  Generated by Enterprise Architect
//  Created on:      31-ago-2010 17:58:44
//  Original author: Marco Salonia
///////////////////////////////////////////////////////////

package com.li.dc.sebc.turboFSE.controller.commands.init
{
	import com.li.dc.sebc.turboFSE.controller.ConstCommand;
	import com.li.dc.sebc.turboFSE.model.ConstDataProxy;
	import com.li.dc.sebc.turboFSE.model.FSEModel;
	import com.li.dc.sebc.turboFSE.view.nodeView.Root;

	import it.lispa.siss.sebc.flex.debug.Debug;
	import it.lispa.siss.sebc.flex.mvc.controller.Controller;
	import it.lispa.siss.sebc.flex.mvc.controller.SequenceCommand;
	import it.lispa.siss.sebc.middleground.entity.Cittadino;

	import mx.styles.StyleManager;

	/**
	 * @author Marco Salonia
	 * @version 1.0
	 * @created 31-ago-2010 17:58:44
	 */
	public class StartApplicationCommand extends SequenceCommand
	{
		public function StartApplicationCommand()
		{
			super();
		}

	    override protected function initialize(): void
	    {
	    	super.initialize();
	    	Debug.logDebug( "StartApplicationCommand.execute " );
	    	/* LoadQueryCommand */
			addCommand(ConstCommand.LOAD_INIT_QUERY);
			/* LoadConfigurationCommand */
			addCommand(ConstCommand.LOAD_CONFIGURATION);
			/* ConfigDebugCommand */
			addCommand(ConstCommand.CONF_DEBUG);
			/* ConfigStartCommand */
			addCommand(ConstCommand.CONF_LABEL);
			/* InterrogaAscoltatoreTestualeCommand */
			//addCommand(ConstCommand.INTERROGA_ASCOLTATORE_TESTUALE);
			/* InterrogaAscoltatoreCDA2Command */
			//addCommand(ConstCommand.INTERROGA_ASCOLTATORE_CDA2);
			/* LoadElencoProvince */
			//addCommand(ConstCommand.LOAD_ELENCO_PROVINCE);
			/* InitSmartCard */
			addCommand(ConstCommand.INIT_SMART_CARD);
			addCommand(ConstCommand.LOAD_PARAMETRI_VARIABILI);
	    }
		override protected function completeSequence(data:Object=null):void
		{
			Debug.logDebug( "StartApplicationCommand.completeSequence " );

			FSEModel.getInstance().retrieveProxy(ConstDataProxy.STATE_STACK).update( Root.STATE_STACK_VISUALIZZA );
			if(data!=null && data is Cittadino)
			{
				Controller.getInstance().executeCommand(ConstCommand.SMART_CARD_CITT_READY,data as Cittadino);
			}
			//StyleManager.loadStyleDeclarations("style-operatore-verde.swf");
		}
	}//end StartApplicationCommand
}